/* oxlint-disable next/no-html-link-for-pages -- Static export uses document navigation; client RSC navigation is unavailable on the host. */
'use client';
import { useState, useEffect, useMemo, useRef, useCallback } from 'react';
import { flushSync } from 'react-dom';
import { Moon, Coins, Shield, Sword, Swords, Flame, FlaskConical, ArrowRight, ArrowLeft, BookOpen, Heart, Backpack, RotateCcw, Sparkles, Trophy, Feather, Crosshair, Eye, Bell, Drum, Sprout, CookingPot, Leaf, Snowflake, TestTube, Hourglass, Cpu, Zap, Wrench, Bird, Castle, Bot, TowerControl, Battery, Coffee, Gem, Clock, Scan, Flower2, Diamond, Pause, Play, FastForward, TrendingUp, GraduationCap, Store, Skull, Check, Search, Volume2, VolumeX } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel, AlertDialogAction, AlertDialogFooter } from '@/components/ui/alert-dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { ITEMS, DEFS, HEROES, TIERS, ENCHANTS, SKILLS, HOURS, itemText, price, sellPrice } from '@/lib/game-data';
import type { Item, HeroId, Enchant } from '@/lib/game-data';
import { newRun, act, slots, xpNeeded, dailyGold, simulate, enemyFor, validSave } from '@/lib/game-engine';
import type { Run, Action, Frame, Combatant, CombatResult } from '@/lib/game-engine';
import { registerGameTools } from '@/lib/game-webmcp';
const ICONS:Record<string,LucideIcon>={sword:Sword,swords:Swords,feather:Feather,crosshair:Crosshair,eye:Eye,bell:Bell,drum:Drum,flame:Flame,flask:FlaskConical,sprout:Sprout,cooking:CookingPot,leaf:Leaf,snow:Snowflake,potion:TestTube,hourglass:Hourglass,shield:Shield,cpu:Cpu,zap:Zap,wrench:Wrench,bird:Bird,castle:Castle,bot:Bot,tower:TowerControl,battery:Battery,coins:Coins,book:BookOpen,cup:Coffee,gem:Gem,clock:Clock,scan:Scan,sparkles:Sparkles,flower:Flower2,diamond:Diamond};
const SAVE_KEY='f9.game.run.v1';
function RelicIcon({id}:{id:string}){const Icon=ICONS[DEFS[id]?.icon]||Gem;return <Icon strokeWidth={1.3}/>}
function color(id:string){const d=DEFS[id];return ['poison','regen'].includes(d.effect)?'green':['shield','freeze','slow'].includes(d.effect)?'blue':d.effect==='damage'||d.effect==='burn'?'orange':'purple'}
function ItemCard({item,onInspect,onBuy,label,disabled}:{item:Item;onInspect:()=>void;onBuy?:()=>void;label?:string;disabled?:boolean}){const d=DEFS[item.id];return <article className={'item-card '+color(item.id)+' tier-'+item.tier}><div className="card-top"><span>{TIERS[item.tier]} · {d.tag}</span><span title={`${d.size} 格`}>{'▪'.repeat(d.size)}</span></div><button className="relic-inspect" onClick={onInspect} aria-label={`查看${d.name}详情`}><div className="relic-icon"><RelicIcon id={item.id}/></div><h3>{d.name}</h3></button><p>{itemText(item)}</p>{d.note&&d.cd>0&&<p className="synergy-note">{d.note}</p>}<footer>{onBuy?<button className="buy-button" disabled={disabled} onClick={onBuy}><span>{label||'收入行囊'}</span><b><Coins/>{price(item)}</b></button>:<button className="text-button" onClick={onInspect}>查看异物 <ArrowRight/></button>}</footer></article>}
function StatBar({unit,side}:{unit:Combatant;side:string}){return <div className={'fighter-stats '+side}><div className="fighter-title"><div><span className="eyebrow">{side==='player'?'YOUR TRAVELER':'OPPONENT'}</span><h3>{unit.name}</h3></div><div className="hp-number"><Heart/>{Math.ceil(unit.hp)}<small>/ {unit.maxHP}</small></div></div><Progress value={Math.max(0,unit.hp/unit.maxHP*100)} aria-label={`${unit.name}生命`} className="hp-progress"/><div className="status-row"><span className="blue-text"><Shield/>{Math.round(unit.shield)} 护盾</span>{unit.poison>0&&<span className="green-text"><FlaskConical/>{unit.poison} 毒</span>}{unit.burn>0&&<span className="orange-text"><Flame/>{unit.burn} 灼烧</span>}{unit.regen>0&&<span className="green-text"><Sprout/>{unit.regen} 再生</span>}</div></div>}
function BattleBoard({unit,frame,onInspect}:{unit:Combatant;frame:Frame;onInspect:(x:Item)=>void}){return <div className="board-grid battle-board">{unit.board.map(x=><button key={x.uid} className={'board-item '+color(x.id)+(frame.fired.includes(x.uid)?' firing':'')+(x.frozen>0?' frozen':'')} style={{gridColumn:`span ${DEFS[x.id].size}`}} onClick={()=>onInspect(x)}><RelicIcon id={x.id}/><strong>{DEFS[x.id].name}</strong><small>{x.frozen>0?'冻结':x.hasted>0?'加速':x.slowed>0?'减速':TIERS[x.tier]}</small>{DEFS[x.id].cd>0?<Progress value={x.ammo===0?0:Math.min(100,x.progress/x.cd*100)} aria-label={`${DEFS[x.id].name}冷却`} className="cooldown-progress"/>:<span className="passive-label">被动</span>}{x.ammo>=0&&<span className="ammo">弹药 {x.ammo}</span>}</button>)}{Array.from({length:Math.max(0,10-slots(unit.board))},(_,i)=><div className="empty-slot" key={i}>·</div>)}</div>}
const choiceData:Record<string,{title:string;description:string;icon:LucideIcon;meta:string}>={curios:{title:'拾月杂货铺',description:'看看命运这次摆上了什么。',icon:Store,meta:'角色异物 / 工具'},weapons:{title:'锈刃铁匠',description:'趁夜色未深，磨利你的锋芒。',icon:Swords,meta:'武器 / 工具'},alchemy:{title:'瓶中的花园',description:'毒、火和一点温柔的治愈。',icon:FlaskConical,meta:'炼金 / 恢复'},train:{title:'流浪学者',description:'有些知识，值得停下脚步。',icon:GraduationCap,meta:'+3 额外经验'},work:{title:'街坊的委托',description:'帮忙修整摊位，挣一笔路费。',icon:Coins,meta:'+5 金'},rest:{title:'月下茶席',description:'片刻休憩，让身心更加坚韧。',icon:Coffee,meta:'+30 最大生命'},invest:{title:'空置的小摊',description:'今夜的投入，换未来的回报。',icon:TrendingUp,meta:'5 金 → 每日收入 +2'},enchant:{title:'刻印师的帐篷',description:'让一件异物，变得不再寻常。',icon:Sparkles,meta:'6 金 / 四种附魔'},skill:{title:'无字书屋',description:'带走一段只属于你的秘闻。',icon:BookOpen,meta:'4 金 / 永久被动'}};
function choices(r:Run){if(r.hour===0)return ['curios','train','invest'];if(r.hour===1)return [r.day%2?'alchemy':'weapons','work','skill'];if(r.hour===2)return ['curios','train','rest'];return ['curios',r.day%2?'enchant':'skill','invest']}
export default function Home(){
 const [run,setRun]=useState<Run>(()=>newRun());const runRef=useRef(run);const [ready,setReady]=useState(false);const [started,setStarted]=useState(false);const [heroesOpen,setHeroesOpen]=useState(false);const [resetOpen,setResetOpen]=useState(false);const [help,setHelp]=useState(false);const [detail,setDetail]=useState<Item|null>(null);const [notice,setNotice]=useState('');const [saveLabel,setSaveLabel]=useState('本机自动存档');const [cursor,setCursor]=useState(0);const [speed,setSpeed]=useState(2);const [paused,setPaused]=useState(false);const [replay,setReplay]=useState(false);const [query,setQuery]=useState('');const [sound,setSound]=useState(false);const audioRef=useRef<AudioContext|null>(null);
 const hero=HEROES.find(h=>h.id===run.hero)!;const combat=useMemo(()=>run.battle?simulate(run.battle):null,[run.battle]);const frame=combat?.frames[Math.min(cursor,combat.frames.length-1)];
 const beep=useCallback(()=>{if(!sound)return;try{const ctx=audioRef.current??(audioRef.current=new AudioContext());void ctx.resume();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.type='sine';osc.frequency.setValueAtTime(440,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(180,ctx.currentTime+.12);gain.gain.setValueAtTime(.045,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.15);osc.start();osc.stop(ctx.currentTime+.16)}catch{}},[sound]);
 const perform=useCallback((action:Action)=>{const next=act(runRef.current,action);runRef.current=next;setRun(next);setNotice(next.notice);return next},[]);
 const dispatch=useCallback((action:Action)=>{try{const next=perform(action);if(action.type==='buy'||action.type==='enchant')beep();if(action.type==='fight'){setCursor(0);setPaused(false);setReplay(false)}if(action.type==='next'){setCursor(0);setReplay(false)}return next}catch(e){setNotice(e instanceof Error?e.message:'操作未完成，请重试。');return null}},[perform,beep]);
 // oxlint-disable-next-line react/react-compiler -- Hydrate browser-local storage after SSR; this is an external-state synchronization.
 useEffect(()=>{try{const saved=localStorage.getItem(SAVE_KEY);if(saved){const parsed:unknown=JSON.parse(saved);if(validSave(parsed)){runRef.current=parsed;setRun(parsed);setStarted(true);setNotice('已恢复本机冒险。');}else{setHeroesOpen(true);setNotice('旧存档无法读取，请开始新的冒险。')}}else setHeroesOpen(true)}catch{setHeroesOpen(true);setSaveLabel('存档不可用')}setReady(true)},[]);
 // oxlint-disable-next-line react/react-compiler -- Report the actual outcome of persisting to external browser storage.
 useEffect(()=>{if(!ready||!started)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify(run));setSaveLabel('本机已保存')}catch{setSaveLabel('存档不可用 · 请勿关闭页面')}},[run,ready,started]);
 useEffect(()=>{if(!started)return;return registerGameTools(()=>runRef.current,(a)=>{let next!:Run;flushSync(()=>{next=perform(a)});return next})},[started,perform]);
 useEffect(()=>{if(!combat||paused||(!replay&&run.phase!=='combat'))return;if(cursor>=combat.frames.length-1){const t=setTimeout(()=>{if(runRef.current.phase==='combat')dispatch({type:'resolve'});setReplay(false)},500);return()=>clearTimeout(t)}const t=setTimeout(()=>setCursor(c=>c+1),200/speed);return()=>clearTimeout(t)},[combat,cursor,paused,speed,run.phase,replay,dispatch]);
 useEffect(()=>{if(frame?.fired.length&&sound&&!paused)beep()},[frame,sound,paused,beep]);
 useEffect(()=>()=>{void audioRef.current?.close()},[]);
 const start=(id:HeroId)=>{const next=newRun(id,crypto.getRandomValues(new Uint32Array(1))[0]);runRef.current=next;setRun(next);setStarted(true);setHeroesOpen(false);setCursor(0);setReplay(false);setPaused(false);setDetail(null);setNotice(next.notice)};
 const locked=['combat','result','ended'].includes(run.phase);const isBattle=!!(run.battle&&combat&&frame&&['combat','result'].includes(run.phase));
 const viewed=detail?([...run.board,...run.stash,...run.shop].find(x=>x.uid===detail.uid)||detail):null;const owned=viewed?[...run.board,...run.stash].some(x=>x.uid===viewed.uid):false;const inBoard=viewed?run.board.some(x=>x.uid===viewed.uid):false;
 function inventory(items:Item[],to:'board'|'stash'){return <div className={'board-grid '+(to==='stash'?'stash-grid':'')} onDragOver={e=>{if(!locked)e.preventDefault()}} onDrop={e=>{e.preventDefault();if(!locked)dispatch({type:'move',uid:e.dataTransfer.getData('text/plain'),to})}}>{items.map((x,i)=><button key={x.uid} draggable={!locked} onDragStart={e=>{e.dataTransfer.setData('text/plain',x.uid);e.dataTransfer.effectAllowed='move'}} onDragOver={e=>{if(!locked)e.preventDefault()}} onDrop={e=>{e.preventDefault();e.stopPropagation();if(!locked)dispatch({type:'move',uid:e.dataTransfer.getData('text/plain'),to,index:i})}} className={'board-item '+color(x.id)+' tier-'+x.tier} style={{gridColumn:`span ${DEFS[x.id].size}`}} onClick={()=>setDetail(x)} aria-label={`查看${DEFS[x.id].name}，${TIERS[x.tier]}，${DEFS[x.id].size}格`}><RelicIcon id={x.id}/><strong>{DEFS[x.id].name}</strong><small>{x.enchant?ENCHANTS[x.enchant].name:TIERS[x.tier]}</small></button>)}{Array.from({length:Math.max(0,10-slots(items))},(_,i)=><div className="empty-slot" key={i}>+</div>)}</div>}
 function battleView(result:CombatResult,f:Frame){return <section className="combat-stage"><div className="combat-heading"><span className="eyebrow">{run.battle!.night?'THE MIDNIGHT DUEL':'WILDERNESS BOUNTY'}</span><span className="stage-badge">{run.battle!.night?'本地生成对手':'荒野悬赏'}</span></div><StatBar unit={f.enemy} side="enemy"/><BattleBoard unit={f.enemy} frame={f} onInspect={setDetail}/><div className="battle-divider"><span/><div className={f.sand?'sand-clock':'duel-clock'}><Swords/><b>{f.time.toFixed(1)}<small> s</small></b>{f.sand>0?<small>沙暴 · {f.sand} 伤害/秒</small>:<small>30 秒后沙暴降临</small>}</div><span/></div><BattleBoard unit={f.player} frame={f} onInspect={setDetail}/><StatBar unit={f.player} side="player"/><div className="battle-controls"><button className="quiet" onClick={()=>setPaused(!paused)} disabled={run.phase==='result'&&!replay}>{paused?<Play/>:<Pause/>}{paused?'继续':'暂停'}</button><button className="quiet" onClick={()=>setSpeed(s=>s===1?2:s===2?4:1)}><FastForward/>{speed}×</button><button className="quiet" disabled={run.phase==='result'&&!replay} onClick={()=>{setCursor(result.frames.length-1);setPaused(false)}}>直接看结果</button><span className="muted">点击异物查看详情</span></div><div className="combat-log" aria-label="战斗记录">{result.frames.slice(Math.max(0,cursor-14),cursor+1).flatMap(x=>x.events.map((event,i)=><p key={x.time+'-'+i}><time>{x.time.toFixed(1)}s</time>{event}</p>)).slice(-6)}</div>{run.phase==='result'&&!replay&&<section className={'result-panel '+(run.lastWin?'victory':'defeat')} aria-label="战斗结算"><div className="result-mark">{run.lastWin?<Trophy/>:<Moon/>}</div><div><div className="eyebrow">{run.lastWin?'VICTORY':'THE NIGHT GOES ON'}</div><h2>{run.lastWin?'这一夜，属于你。':'收好行囊，再赴长夜。'}</h2><p>{run.notice||run.log[0]}</p><small>历时 {result.duration.toFixed(1)} 秒 · 我方输出 {result.playerDamage} / 对方输出 {result.enemyDamage}</small></div><div className="result-actions"><button className="primary" onClick={()=>dispatch({type:'next'})}>{run.wins>=10||run.prestige<=0?'查看结局':run.battle!.night?'迎接新的一天':'继续旅程'}<ArrowRight/></button><button className="text-button" onClick={()=>{setReplay(true);setCursor(0);setPaused(false)}}><RotateCcw/>回看战斗</button></div></section>}</section>}
 return <main className="game-shell"><header className="topbar"><a className="wordmark" href="/" aria-label="f9 game 首页">f9<span>game</span><i>午夜异物集市</i></a><div className="run-stats"><span><Moon/>第 {run.day} 天</span><span title="午夜败北扣除当天的天数；归零可重生一次。"><Heart/>声望 {Math.max(0,run.prestige)}</span><span className="gold"><Coins/>{run.gold}<small>+{run.income}/日</small></span></div><div className="header-actions"><button className="quiet icon-button" onClick={()=>setSound(!sound)} aria-label={sound?'关闭音效':'开启音效'} aria-pressed={sound}>{sound?<Volume2/>:<VolumeX/>}</button><button className="quiet" onClick={()=>setHelp(true)}><BookOpen/><span>游玩手册</span></button></div></header>
 <div className="game-layout"><aside className="journey"><div className="eyebrow">YOUR JOURNEY</div><h2>漫游第 {run.day} 夜</h2><p className="muted">十场胜利，一段传奇。</p><div className="wins" aria-label={`${run.wins} 场胜利，目标十胜`}>{Array.from({length:10},(_,i)=><span key={i} className={i<run.wins?'won':''}>◆</span>)}</div><div className="win-caption">{run.wins} / 10 枚胜印{run.rescued&&<span>已用绝境重生</span>}</div><div className="journey-stops">{HOURS.map((t,i)=><div className={'stop '+(i===run.hour?'active':i<run.hour?'complete':'')} key={t}><span>{i<run.hour?<Check/>:i===5?<Moon/>:String(i+1).padStart(2,'0')}</span><div>{t}<small>{i===run.hour?'你在这里':i<run.hour?'已走过':i===5?'自动战斗':'选择你的道路'}</small></div></div>)}</div><div className="traveler"><span className="eyebrow">{hero.role}</span><h3>{hero.name} <small>Lv.{run.level}</small></h3><div className="traveler-stats"><span><Heart/>{run.hp} 生命</span><span><Coins/>{dailyGold(run)} 预计日结</span></div><Progress value={run.xp/xpNeeded(run)*100} aria-label="等级经验" className="xp-progress"/><small>经验 {run.xp} / {xpNeeded(run)}</small></div><div className="aside-note">强大的不是单件异物，<br/>而是它们之间的联系。</div><button className="text-button new-run-link" onClick={()=>setResetOpen(true)}><RotateCcw/>重新启程</button></aside>
 <section className="play-space"><div className="section-heading"><div><div className="eyebrow">{isBattle?'THE NIGHT REMEMBERS':'THE MIDNIGHT MARKET'}</div><h1>{isBattle?'让你的异物，替你开口。':run.phase==='ended'?'旅程终有回响。':run.phase==='choice'?'下一步，走向何处？':'好东西，都有一点古怪。'}</h1></div><span className="stage-badge">{HOURS[run.hour]} · {run.phase==='shop'?'交易':isBattle?'对决':'冒险'}</span></div>
 {isBattle?battleView(combat!,frame!):run.phase==='ended'?<section className="ending"><Trophy className="ending-icon"/><div className="eyebrow">{run.wins>=10?'LEGEND OF THE MIDNIGHT MARKET':'UNTIL THE NEXT MOON'}</div><h2>{run.endedReason}</h2><p>{run.wins>=10?'你带着十枚胜印走出集市，黎明为你让路。':'长夜收走了最后的声望。但下一次，你会带着经验归来。'}</p><div className="ending-stats"><span><b>{run.wins}</b>胜印</span><span><b>{run.day}</b>天旅程</span><span><b>{run.level}</b>等级</span></div><button className="primary" onClick={()=>setHeroesOpen(true)}>开始新的旅程 <ArrowRight/></button><button className="text-button" onClick={()=>setHelp(true)}>查看图鉴，筹划新的搭配</button></section>:<>
 <section className={'merchant-stage '+(run.phase!=='shop'?'compact-stage':'')}><div className="merchant-copy"><span className="eyebrow">NO. 09 / THE CURIOSITY SHOP</span><h2>{run.phase==='enchant'?'月下刻印':run.phase==='skill'?'无字书屋':run.phase==='choice'&&run.hour===5?'午夜将至':run.phase==='shop'&&run.merchant==='weapons'?'锈刃铁匠':run.phase==='shop'&&run.merchant==='alchemy'?'瓶中的花园':'拾月杂货铺'}</h2><p>{run.phase==='choice'?'「每一条路，都会在你的行囊里留下痕迹。」':'「不问来处，只问你敢不敢带走。」'}</p><span className="merchant-label">异物商人 · 蛾先生</span></div></section>
 {run.phase==='shop'&&<><div className="shop-toolbar"><span>今日陈列 <small>同名异物升级 · 不重复占格</small></span><button className="quiet" disabled={run.gold<2+run.rerolls} onClick={()=>dispatch({type:'reroll'})}><RotateCcw/>刷新 · {2+run.rerolls} 金</button></div><div className="shop-grid">{run.shop.map((x,i)=>{const duplicate=[...run.board,...run.stash].find(y=>y.id===x.id);return <ItemCard key={x.uid} item={x} onInspect={()=>setDetail(x)} onBuy={()=>dispatch({type:'buy',index:i})} disabled={run.gold<price(x)||duplicate?.tier===3} label={duplicate?duplicate.tier===3?'已达最高品质':`升级至${TIERS[Math.min(3,Math.max(duplicate.tier+1,x.tier))]}`:'收入行囊'}/>})}{run.shop.length===0&&<div className="sold-out"><Check/><h3>好东西都有了归宿。</h3><p>刷新陈列，或继续你的旅程。</p></div>}</div></>}
 {run.phase==='choice'&&run.hour!==3&&run.hour!==5&&<div className="choices-grid">{choices(run).map(kind=>{const c=choiceData[kind];return <button className="choice-card" key={kind} onClick={()=>dispatch({type:'choose',kind})}><c.icon/><span className="eyebrow">{c.meta}</span><h3>{c.title}</h3><p>{c.description}</p><span className="choice-go">前往此处 <ArrowRight/></span></button>})}</div>}
 {run.phase==='choice'&&run.hour===3&&<><div className="shop-toolbar"><span>荒野悬赏 <small>胜利获得金币与经验，失败不扣声望</small></span><button className="quiet" onClick={()=>dispatch({type:'choose',kind:'rest'})}>休息 · 生命 +30</button></div><div className="choices-grid">{[0,1,2].map(n=>{const enemy=enemyFor(run,n,false);return <button className={'choice-card monster difficulty-'+n} key={n} onClick={()=>dispatch({type:'fight',difficulty:n})}><Skull/><span className="eyebrow">{['低风险','中风险','高风险'][n]} / {enemy.hp} 生命</span><h3>{enemy.name}</h3><p>{enemy.board.map(x=>DEFS[x.id].name).join(' · ')}</p><span className="choice-go">{[4,7,11][n]} 金 · {[2,3,5][n]} 经验 <Swords/></span></button>})}</div></>}
 {run.phase==='choice'&&run.hour===5&&<div className="night-preview"><div><span className="eyebrow">NEXT OPPONENT / 本地生成阵容</span><h3>{enemyFor(run,1,true).name}</h3><p>{enemyFor(run,1,true).hp} 生命 · 失败扣除 {run.day} 声望</p><span>{enemyFor(run,1,true).board.map(x=>DEFS[x.id].name).join(' · ')}</span></div><button className="primary" onClick={()=>dispatch({type:'fight',difficulty:1})}><Swords/>进入午夜对决</button></div>}
 {run.phase==='enchant'&&<div className="enchant-area"><p className="muted">选择一件有冷却的异物，再选择刻印。花费 6 金，新刻印会替换旧刻印。</p><div className="enchant-items">{[...run.board,...run.stash].filter(x=>DEFS[x.id].cd>0).map(x=><div className="enchant-row" key={x.uid}><span><RelicIcon id={x.id}/>{DEFS[x.id].name}{x.enchant&&<small> · {ENCHANTS[x.enchant].name}</small>}</span><div>{(Object.keys(ENCHANTS) as Enchant[]).map(enchant=><button title={ENCHANTS[enchant].description} key={enchant} className="quiet" disabled={run.gold<6} onClick={()=>dispatch({type:'enchant',uid:x.uid,enchant})}>{ENCHANTS[enchant].name}</button>)}</div></div>)}</div><div className="enchant-legend">{Object.values(ENCHANTS).map(e=><span key={e.name}>{e.name}：{e.description}</span>)}</div></div>}
 {run.phase==='skill'&&<div className="choices-grid">{run.skillOffers.map(id=>{const skill=SKILLS.find(s=>s.id===id)!;return <button key={id} className="choice-card" disabled={run.gold<4} onClick={()=>dispatch({type:'skill',id})}><BookOpen/><span className="eyebrow">永久技能 / 4 金</span><h3>{skill.name}</h3><p>{skill.description}</p><span className="choice-go">领悟 <ArrowRight/></span></button>})}{!run.skillOffers.length&&<p className="muted">所有秘闻皆已领悟，继续旅程吧。</p>}</div>}
 </>}
 {!isBattle&&<section className="board-section"><div className="shop-toolbar"><span><Swords/>你的战斗行囊 <small>拖动排列 / 点击管理</small></span><span className="capacity">{slots(run.board)} / 10 格</span></div>{inventory(run.board,'board')}<div className="board-bottom"><span><Sparkles/>相邻联动依实际排列生效</span>{['shop','enchant','skill'].includes(run.phase)&&<button className="primary" onClick={()=>dispatch({type:'leave'})}>{run.phase==='shop'?'离开商店':'离开此处'}<ArrowRight/></button>}</div><div className="stash-heading"><span><Backpack/>仓库 <small>{slots(run.stash)} / 10 格 · 仓库物品不参战</small></span></div>{inventory(run.stash,'stash')}</section>}
 {run.skills.length>0&&<div className="skills-strip"><span className="muted">已领悟</span>{run.skills.map(id=><button className="skill-chip" key={id} title={SKILLS.find(s=>s.id===id)!.description} onClick={()=>setNotice(SKILLS.find(s=>s.id===id)!.description)}><Sparkles/>{SKILLS.find(s=>s.id===id)!.name}</button>)}</div>}
 <output className="notice" aria-live="polite">{notice||run.notice||'点击异物查看详细效果，拖动调整排列。'}</output><div className="mobile-run-actions"><span>{hero.name} Lv.{run.level} · {run.hp} 生命</span><button className="text-button" onClick={()=>setResetOpen(true)}><RotateCcw/>重新启程</button></div>
 </section></div><footer className="site-footer"><span>f9 / 午夜异物集市 · 单人冒险</span><span>{saveLabel} · 筹划于白昼，决胜于午夜</span></footer>
 <Dialog open={heroesOpen} onOpenChange={open=>{if(started)setHeroesOpen(open)}}><DialogContent className="hero-dialog" showCloseButton={started}><DialogTitle className="dialog-heading">今夜，谁来赴约？</DialogTitle><DialogDescription>选择一位旅人，带着独有的异物与天赋，走入午夜集市。</DialogDescription><div className="hero-grid">{HEROES.map(h=>{const Icon=ICONS[h.icon];return <button className={'hero-card '+h.color} key={h.id} disabled={!ready} onClick={()=>start(h.id)}><Icon strokeWidth={1}/><span className="eyebrow">{h.role}</span><h2>{h.name}</h2><p>{h.title}</p><div className="hero-description">{h.description}</div><div className="hero-start"><span>生命 {h.hp} · 日收入 {h.income}</span><ArrowRight/></div></button>})}</div><p className="muted">每局目标十胜。经营阶段没有倒计时，所有战斗自动进行。</p></DialogContent></Dialog>
 <Dialog open={!!viewed} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="item-dialog">{viewed&&<><div className={'detail-art '+color(viewed.id)}><RelicIcon id={viewed.id}/></div><DialogTitle className="dialog-heading">{DEFS[viewed.id].name}</DialogTitle><DialogDescription>{TIERS[viewed.tier]} · {DEFS[viewed.id].tag} · 占用 {DEFS[viewed.id].size} 格</DialogDescription><p>{itemText(viewed)}</p>{DEFS[viewed.id].cd>0&&DEFS[viewed.id].note&&<p className="detail-note">{DEFS[viewed.id].note}</p>}{viewed.enchant&&<p className="gold">{ENCHANTS[viewed.enchant].name}：{ENCHANTS[viewed.enchant].description}</p>}<p className="muted">显示物品基础效力；角色、技能与邻接加成在战斗中生效。</p>{owned&&!locked&&<div className="item-actions"><button className="primary" onClick={()=>{if(dispatch({type:'move',uid:viewed.uid,to:inBoard?'stash':'board'}))setDetail(null)}}><Backpack/>{inBoard?'移入仓库':'装备到行囊'}</button><div className="reorder-buttons"><button className="quiet" disabled={(inBoard?run.board:run.stash).findIndex(x=>x.uid===viewed.uid)===0} onClick={()=>dispatch({type:'move',uid:viewed.uid,to:inBoard?'board':'stash',index:(inBoard?run.board:run.stash).findIndex(x=>x.uid===viewed.uid)-1})}><ArrowLeft/>左移</button><button className="quiet" disabled={(inBoard?run.board:run.stash).at(-1)?.uid===viewed.uid} onClick={()=>dispatch({type:'move',uid:viewed.uid,to:inBoard?'board':'stash',index:(inBoard?run.board:run.stash).findIndex(x=>x.uid===viewed.uid)+1})}>右移<ArrowRight/></button></div><button className="quiet sell-button" onClick={()=>{if(dispatch({type:'sell',uid:viewed.uid}))setDetail(null)}}><Coins/>出售 · {sellPrice(viewed)} 金</button></div>}<output className="dialog-status">{notice}</output></>}</DialogContent></Dialog>
 <Dialog open={run.pendingLevel>0&&run.phase!=='combat'&&started} onOpenChange={()=>{}}><DialogContent className="level-dialog" showCloseButton={false}><Sparkles className="level-icon"/><DialogTitle className="dialog-heading">旅人成长 · Lv.{run.level}</DialogTitle><DialogDescription>升级已获得 45 最大生命，再选择一项永久奖励。{run.pendingLevel>1?`待领取 ${run.pendingLevel} 次。`:''}</DialogDescription><div className="level-choices">{[{id:'power',name:'锋芒与守护',text:'武器伤害 +6，护盾效力 +8',icon:Swords},{id:'vitality',name:'长夜之躯',text:'最大生命 +75',icon:Heart},{id:'income',name:'生意经',text:'每日收入 +2 金',icon:Coins}].map(c=><button className="level-choice" key={c.id} onClick={()=>dispatch({type:'level',choice:c.id})}><c.icon/><span><strong>{c.name}</strong><small>{c.text}</small></span><ArrowRight/></button>)}</div></DialogContent></Dialog>
 <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent className="reset-dialog"><AlertDialogTitle>结束这次旅程？</AlertDialogTitle><AlertDialogDescription>当前第 {run.day} 天、{run.wins} 胜的进度会在选择新旅人后被替换。</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>继续当前旅程</AlertDialogCancel><AlertDialogAction onClick={()=>{setResetOpen(false);setHeroesOpen(true)}}>选择新旅人</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogTitle className="dialog-heading">午夜旅行手册</DialogTitle><DialogDescription>学会挑选，学会舍弃，让异物彼此成就。</DialogDescription><Tabs defaultValue="rules"><TabsList><TabsTrigger value="rules">游玩规则</TabsTrigger><TabsTrigger value="items">异物图鉴 · {ITEMS.length}</TabsTrigger><TabsTrigger value="research">调研与说明</TabsTrigger></TabsList><TabsContent value="rules"><div className="rules-grid"><section><h3>01 / 经营你的白天</h3><p>每天六个时辰。逛店、求学、做委托或投资会推进旅程；商店内可多次购买。第四时辰选择悬赏，最后在午夜迎战。</p></section><section><h3>02 / 构筑你的行囊</h3><p>战斗区与仓库各十格。小、中、大异物占 1、2、3 格。购买同名物品会升级至更高品质，无需两件都留着。拖动排列，或点击后使用左右移动按钮。</p></section><section><h3>03 / 异物自己战斗</h3><p>每件主动异物按自己的冷却触发。护盾抵挡普通伤害及灼烧；毒每秒直接扣生命，绕过护盾。灼烧每秒结算并衰减一层。再生每秒恢复生命，生命归零即败北。</p></section><section><h3>04 / 把联动放对位置</h3><p>相邻指左右紧挨的异物。走时扳手降低邻居冷却，独眼镜片提高相邻武器暴击率。加速使计时翻倍，减速减半，冻结暂停计时。战斗三十秒后沙暴持续增强。</p></section><section><h3>05 / 投资与成长</h3><p>新一天领取日收入，另有每十金币一金利息（上限五金）。吞金钱袋在仓库也能带来日结收益。升级获得生命与三选一奖励；技能和附魔拓展构筑。</p></section><section><h3>06 / 带着十枚胜印归来</h3><p>只计算午夜胜利。失败损失等于当天数的声望。初始声望二十，首次归零时获得一次绝境救援；再次归零则结束。悬赏失败不扣声望。每场战斗从满生命开始。</p></section></div><div className="build-tips"><h3>可以试试这些搭配</h3><p>鸦九：月蚀细剑 + 独眼镜片 + 渡鸦风铃，专注唯一武器。</p><p>苔婆：苔毒试剂 + 夜沸坩埚 + 玻璃温室，让毒火不断成长。</p><p>拾壹：发条心脏 + 纸翼侍从 + 雷鸣线圈，把护盾变成攻击。</p></div></TabsContent><TabsContent value="items"><label className="atlas-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索名称、类型或效果" aria-label="搜索异物图鉴"/></label><div className="atlas-grid">{ITEMS.filter(d=>(d.name+d.tag+(d.note||'')+itemText({uid:'atlas-'+d.id,id:d.id,tier:0,bonus:0})).includes(query)).map(d=>{const x={uid:'atlas-'+d.id,id:d.id,tier:0,bonus:0};return <ItemCard key={d.id} item={x} onInspect={()=>{setHelp(false);setDetail(x)}}/>})}</div>{!ITEMS.some(d=>(d.name+d.tag+(d.note||'')+itemText({uid:'',id:d.id,tier:0,bonus:0})).includes(query))&&<p className="muted">没有找到对应异物。</p>}</TabsContent><TabsContent value="research"><div className="research-copy"><h3>源于 The Bazaar 的核心机制研究</h3><p>保留“日间经营 → 物品构筑 → 独立冷却自动战斗 → 成长与十胜”的核心循环。角色、美术、物品、文案和数值均为 f9 原创。</p><p>本版为可完整游玩的单人版本。午夜对手按天数生成，不是真实玩家快照；存档保存在当前浏览器，不跨设备同步。完整原作的物品池、排位与服务器匹配不在本版中。</p><p>调研于 2026 年 9 月 6 日。原作持续更新，本版采用独立数值与经典声望规则，不声称逐补丁一致。</p><ul><li><a href="https://store.steampowered.com/app/1617400/The_Bazaar/" target="_blank" rel="noreferrer">Tempo 官方游戏介绍 ↗</a></li><li><a href="https://mobalytics.gg/the-bazaar/guides/beginner-guide" target="_blank" rel="noreferrer">入门与异步对战流程 ↗</a></li><li><a href="https://thebazaar.wiki.gg/wiki/Items" target="_blank" rel="noreferrer">物品格位、品质与升级 ↗</a></li><li><a href="https://mobalytics.gg/the-bazaar/guides/keywords-and-terms" target="_blank" rel="noreferrer">冷却与状态关键词 ↗</a></li><li><a href="https://mobalytics.gg/the-bazaar/guides/prestige" target="_blank" rel="noreferrer">经典声望规则 ↗</a></li></ul></div></TabsContent></Tabs></DialogContent></Dialog>
 </main>
}
