import { CARDS as ORIGINAL, type CardDef } from './prototype-v04.ts';
export type School = 'rush' | 'erosion' | 'bastion';
export type SystemCard = CardDef & {
  school?: School;
  rarity?: number;
  role?: string;
  rule?: string;
};
const make = (
  id: string,
  name: string,
  size: number,
  cd: number,
  power: number,
  kind: string,
  school: School,
  rarity: number,
  role: string,
  rule: string,
): SystemCard => ({
  id,
  name,
  size,
  cd,
  power,
  kind,
  school,
  rarity,
  role,
  rule,
  energyCost: 0,
  energyGain: 0,
  effect: rule,
  master: rule,
});
export const SYSTEM_CARDS: SystemCard[] = [
  make(
    'nailer',
    '破门钉枪',
    2,
    3,
    16,
    'damage',
    'rush',
    1,
    '启动 / 输出',
    '前两次发动额外造成 16 伤害；升阶每次额外伤害 +4。',
  ),
  make(
    'fuse',
    '引信线',
    1,
    5,
    1,
    'charge',
    'rush',
    0,
    '启动 / 辅助',
    '给同路另一张牌充能；首次发动额外充能 2 秒，升阶每阶 +0.5 秒。',
  ),
  make(
    'gapblade',
    '猎隙刃',
    1,
    3,
    10,
    'damage',
    'rush',
    0,
    '突破后输出',
    '命中时目标屏障已损毁，则伤害 +12；升阶每阶再 +4。',
  ),
  make(
    'springbow',
    '卷簧弩',
    2,
    5,
    22,
    'damage',
    'rush',
    2,
    '爆发输出',
    '前三次发动伤害 +16；升阶每阶再 +4。后续恢复基础伤害。',
  ),
  make(
    'recoil',
    '反冲板',
    2,
    4,
    24,
    'damage',
    'bastion',
    1,
    '反击输出',
    '本路屏障实际承伤的 50% 储为反冲，最多 40；下次攻击消耗并附加。升阶上限每阶 +10。',
  ),
  make(
    'sealant',
    '补漏胶',
    1,
    3,
    28,
    'shield',
    'bastion',
    0,
    '修复',
    '修复本路屏障；本路损毁后支援其他仍存活且剩余比例最低的屏障。',
  ),
  make(
    'rubber',
    '缓冲垫',
    1,
    6,
    4,
    'shield',
    'bastion',
    1,
    '缓冲 / 防御',
    '本路完整屏障每次受到弹道伤害时减少 8，升阶每阶 +1。同路仅取最高值；不能减免侵蚀。',
  ),
  make(
    'counterweight',
    '配重锤',
    2,
    5,
    18,
    'damage',
    'bastion',
    2,
    '防守转输出',
    '发动时本路屏障高于 50%，伤害 +20；升阶每阶再 +5。',
  ),
  make(
    'acid',
    '蚀液喷壶',
    2,
    5,
    4,
    'corrode',
    'erosion',
    1,
    '侵蚀引擎',
    '同路叠加侵蚀，每层每秒造成 1 伤害并削减 1 屏障上限；本路最多 12 层。升阶每阶多叠 1 层。',
  ),
  make(
    'culture',
    '培养皿',
    2,
    5,
    8,
    'damage',
    'erosion',
    2,
    '成长输出',
    '优先攻击侵蚀最深的一路（同层数优先上路）；每次发动永久增加本场伤害 8（第一次无增幅）；升阶每阶增加 2。',
  ),
  make(
    'catalyst',
    '催化管',
    1,
    4,
    0.8,
    'charge',
    'erosion',
    0,
    '侵蚀 / 辅助',
    '给同路另一张牌充能；敌方本路有侵蚀时额外充能 0.8 秒，升阶每阶 +0.2 秒。',
  ),
  make(
    'distiller',
    '蒸馏器',
    1,
    7,
    1,
    'corrode',
    'erosion',
    1,
    '续航 / 侵蚀',
    '同路叠加侵蚀，同时治疗宿主 5；升阶每阶治疗 +3，侵蚀多叠 1 层。',
  ),
];
export const CARDS: SystemCard[] = [...ORIGINAL, ...SYSTEM_CARDS];
export const cardDef = (id: string) => {
  const c = CARDS.find((c) => c.id === id);
  if (!c) throw Error('未知卡牌');
  return c;
};
export const SCHOOLS = {
  rush: '速攻突破',
  erosion: '侵蚀成长',
  bastion: '固守反击',
};
